# Generated by Django 4.0.4 on 2022-04-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorname',
            field=models.CharField(choices=[('Viettel IDC', 'Viettel IDC'), ('Microsoft', 'Microsoft')], max_length=200),
        ),
    ]
